//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_address_entry.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelAddressEntry extends _ModelAddressEntry {
  //
  //
  //

  static const CLASS_NAME = 'ModelAddressEntry';

  @override
  String get $className => CLASS_NAME;

  final String? id;
  final DataRefModel? ref;
  final ModelQueryable? displayName;
  final Color? displayColor;
  final String? description;
  final ModelRegistration? archivedGReg;
  final ModelRegistration? createdGReg;
  final ModelRegistration? deletedGReg;
  final ModelRegistration? updatedGReg;
  final DateTime? expiresAt;
  final String? addressLine1;
  final String? addressLine2;
  final String? city;
  final String? stateOrProvince;
  final String? postalCode;
  final String? country;

  //
  //
  //

  const ModelAddressEntry({
    this.id,
    this.ref,
    this.displayName,
    this.displayColor,
    this.description,
    this.archivedGReg,
    this.createdGReg,
    this.deletedGReg,
    this.updatedGReg,
    this.expiresAt,
    this.addressLine1,
    this.addressLine2,
    this.city,
    this.stateOrProvince,
    this.postalCode,
    this.country,
  });

  const ModelAddressEntry.c2({
    this.id,
    this.ref,
    this.displayName,
    this.displayColor,
    this.description,
    this.archivedGReg,
    this.createdGReg,
    this.deletedGReg,
    this.updatedGReg,
    this.expiresAt,
    this.addressLine1,
    this.addressLine2,
    this.city,
    this.stateOrProvince,
    this.postalCode,
    this.country,
  });

  factory ModelAddressEntry.c3({
    String? id,
    DataRefModel? ref,
    ModelQueryable? displayName,
    Color? displayColor,
    String? description,
    ModelRegistration? archivedGReg,
    ModelRegistration? createdGReg,
    ModelRegistration? deletedGReg,
    ModelRegistration? updatedGReg,
    DateTime? expiresAt,
    String? addressLine1,
    String? addressLine2,
    String? city,
    String? stateOrProvince,
    String? postalCode,
    String? country,
  }) {
    return ModelAddressEntry(
      id: id,
      ref: ref,
      displayName: displayName,
      displayColor: displayColor,
      description: description,
      archivedGReg: archivedGReg,
      createdGReg: createdGReg,
      deletedGReg: deletedGReg,
      updatedGReg: updatedGReg,
      expiresAt: expiresAt,
      addressLine1: addressLine1,
      addressLine2: addressLine2,
      city: city,
      stateOrProvince: stateOrProvince,
      postalCode: postalCode,
      country: country,
    );
  }

  factory ModelAddressEntry.from(
    BaseModel? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelAddressEntry.from: $e');
      rethrow;
    }
  }

  static ModelAddressEntry? fromOrNull(
    BaseModel? other,
  ) {
    return fromJsonOrNull(other?.toJson())!;
  }

  factory ModelAddressEntry.of(
    ModelAddressEntry other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelAddressEntry.of: $e');
      rethrow;
    }
  }

  static ModelAddressEntry? ofOrNull(
    ModelAddressEntry? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  factory ModelAddressEntry.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, 'ModelAddressEntry.fromJsonString: $e');
      rethrow;
    }
  }

  static ModelAddressEntry? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelAddressEntry.fromJson(decoded);
      } else {
        return const ModelAddressEntry.c2();
      }
    } catch (_) {
      return null;
    }
  }

  factory ModelAddressEntry.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, 'ModelAddressEntry.fromJson: $e');
      rethrow;
    }
  }

  static ModelAddressEntry? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      final id0 = otherData?[ModelAddressEntryFields.id.name];
      final id = id0?.toString().trim().nullIfEmpty;
      final ref0 = otherData?[ModelAddressEntryFields.ref.name];
      final ref = () {
        final a = letMap<String, dynamic>(ref0);
        return a != null ? DataRefModel.fromJson(a) : null;
      }();
      final displayName0 = otherData?[ModelAddressEntryFields.displayName.name];
      final displayName = () {
        final a = letMap<String, dynamic>(displayName0);
        return a != null ? ModelQueryable.fromJson(a) : null;
      }();
      final displayColor0 =
          otherData?[ModelAddressEntryFields.displayColor.name];
      final displayColor = () {
        final a = letAs<int>(displayColor0);
        return a is int ? Color(a) : null;
      }();
      final description0 = otherData?[ModelAddressEntryFields.description.name];
      final description = description0?.toString().trim().nullIfEmpty;
      final archivedGReg0 =
          otherData?[ModelAddressEntryFields.archivedGReg.name];
      final archivedGReg = () {
        final a = letMap<String, dynamic>(archivedGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final createdGReg0 = otherData?[ModelAddressEntryFields.createdGReg.name];
      final createdGReg = () {
        final a = letMap<String, dynamic>(createdGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final deletedGReg0 = otherData?[ModelAddressEntryFields.deletedGReg.name];
      final deletedGReg = () {
        final a = letMap<String, dynamic>(deletedGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final updatedGReg0 = otherData?[ModelAddressEntryFields.updatedGReg.name];
      final updatedGReg = () {
        final a = letMap<String, dynamic>(updatedGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final expiresAt0 = otherData?[ModelAddressEntryFields.expiresAt.name];
      final expiresAt = () {
        final a = expiresAt0;
        return a != null ? DateTime.tryParse(a)?.toUtc() : null;
      }();
      final addressLine10 =
          otherData?[ModelAddressEntryFields.addressLine1.name];
      final addressLine1 = addressLine10?.toString().trim().nullIfEmpty;
      final addressLine20 =
          otherData?[ModelAddressEntryFields.addressLine2.name];
      final addressLine2 = addressLine20?.toString().trim().nullIfEmpty;
      final city0 = otherData?[ModelAddressEntryFields.city.name];
      final city = city0?.toString().trim().nullIfEmpty;
      final stateOrProvince0 =
          otherData?[ModelAddressEntryFields.stateOrProvince.name];
      final stateOrProvince = stateOrProvince0?.toString().trim().nullIfEmpty;
      final postalCode0 = otherData?[ModelAddressEntryFields.postalCode.name];
      final postalCode = postalCode0?.toString().trim().nullIfEmpty;
      final country0 = otherData?[ModelAddressEntryFields.country.name];
      final country = country0?.toString().trim().nullIfEmpty;
      return ModelAddressEntry(
        id: id,
        ref: ref,
        displayName: displayName,
        displayColor: displayColor,
        description: description,
        archivedGReg: archivedGReg,
        createdGReg: createdGReg,
        deletedGReg: deletedGReg,
        updatedGReg: updatedGReg,
        expiresAt: expiresAt,
        addressLine1: addressLine1,
        addressLine2: addressLine2,
        city: city,
        stateOrProvince: stateOrProvince,
        postalCode: postalCode,
        country: country,
      );
    } catch (e) {
      return null;
    }
  }

  factory ModelAddressEntry.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, 'ModelAddressEntry.fromUri: $e');
      rethrow;
    }
  }

  static ModelAddressEntry? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS_NAME) {
        return ModelAddressEntry.fromJson(uri.queryParameters);
      } else {
        return const ModelAddressEntry.c2();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final id0 = this.id?.trim().nullIfEmpty;
      final ref0 = this.ref?.toJson();
      final displayName0 = this.displayName?.toJson();
      final displayColor0 = this.displayColor?.value;
      final description0 = this.description?.trim().nullIfEmpty;
      final archivedGReg0 = this.archivedGReg?.toJson();
      final createdGReg0 = this.createdGReg?.toJson();
      final deletedGReg0 = this.deletedGReg?.toJson();
      final updatedGReg0 = this.updatedGReg?.toJson();
      final expiresAt0 = this.expiresAt?.toUtc()?.toIso8601String();
      final addressLine10 = this.addressLine1?.trim().nullIfEmpty;
      final addressLine20 = this.addressLine2?.trim().nullIfEmpty;
      final city0 = this.city?.trim().nullIfEmpty;
      final stateOrProvince0 = this.stateOrProvince?.trim().nullIfEmpty;
      final postalCode0 = this.postalCode?.trim().nullIfEmpty;
      final country0 = this.country?.trim().nullIfEmpty;
      final withNulls = <String, dynamic>{
        ModelAddressEntryFields.id.name: id0,
        ModelAddressEntryFields.ref.name: ref0,
        ModelAddressEntryFields.displayName.name: displayName0,
        ModelAddressEntryFields.displayColor.name: displayColor0,
        ModelAddressEntryFields.description.name: description0,
        ModelAddressEntryFields.archivedGReg.name: archivedGReg0,
        ModelAddressEntryFields.createdGReg.name: createdGReg0,
        ModelAddressEntryFields.deletedGReg.name: deletedGReg0,
        ModelAddressEntryFields.updatedGReg.name: updatedGReg0,
        ModelAddressEntryFields.expiresAt.name: expiresAt0,
        ModelAddressEntryFields.addressLine1.name: addressLine10,
        ModelAddressEntryFields.addressLine2.name: addressLine20,
        ModelAddressEntryFields.city.name: city0,
        ModelAddressEntryFields.stateOrProvince.name: stateOrProvince0,
        ModelAddressEntryFields.postalCode.name: postalCode0,
        ModelAddressEntryFields.country.name: country0,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, 'ModelAddressEntry.toJson: $e');
      rethrow;
    }
  }

  //
  //
  //

  @override
  ModelAddressEntry copyWith(BaseModel? other) {
    final a = this.toJson();
    final b = other?.toJson();
    final c = {...a, ...?b};
    return ModelAddressEntry.fromJson(c);
  }

  //
  //
  //

  // id.
  String? get idField => this.id;

  // ref.
  DataRefModel? get refField => this.ref;

  // displayName.
  ModelQueryable? get displayNameField => this.displayName;

  // displayColor.
  Color? get displayColorField => this.displayColor;

  // description.
  String? get descriptionField => this.description;

  // archivedGReg.
  ModelRegistration? get archivedGRegField => this.archivedGReg;

  // createdGReg.
  ModelRegistration? get createdGRegField => this.createdGReg;

  // deletedGReg.
  ModelRegistration? get deletedGRegField => this.deletedGReg;

  // updatedGReg.
  ModelRegistration? get updatedGRegField => this.updatedGReg;

  // expiresAt.
  DateTime? get expiresAtField => this.expiresAt;

  // addressLine1.
  String? get addressLine1Field => this.addressLine1;

  // addressLine2.
  String? get addressLine2Field => this.addressLine2;

  // city.
  String? get cityField => this.city;

  // stateOrProvince.
  String? get stateOrProvinceField => this.stateOrProvince;

  // postalCode.
  String? get postalCodeField => this.postalCode;

  // country.
  String? get countryField => this.country;
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

enum ModelAddressEntryFields {
  //
  //
  //

  id(
    const Field(
      fieldName: 'id',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  ref(
    const Field(
      fieldName: 'ref',
      fieldType: 'DataRefModel',
      nullable: true,
    ),
  ),
  displayName(
    const Field(
      fieldName: 'displayName',
      fieldType: 'ModelQueryable',
      nullable: true,
    ),
  ),
  displayColor(
    const Field(
      fieldName: 'displayColor',
      fieldType: 'Color',
      nullable: true,
    ),
  ),
  description(
    const Field(
      fieldName: 'description',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  archivedGReg(
    const Field(
      fieldName: 'archivedGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  createdGReg(
    const Field(
      fieldName: 'createdGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  deletedGReg(
    const Field(
      fieldName: 'deletedGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  updatedGReg(
    const Field(
      fieldName: 'updatedGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  expiresAt(
    const Field(
      fieldName: 'expiresAt',
      fieldType: 'DateTime',
      nullable: true,
    ),
  ),
  addressLine1(
    const Field(
      fieldName: 'addressLine1',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  addressLine2(
    const Field(
      fieldName: 'addressLine2',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  city(
    const Field(
      fieldName: 'city',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  stateOrProvince(
    const Field(
      fieldName: 'stateOrProvince',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  postalCode(
    const Field(
      fieldName: 'postalCode',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  country(
    const Field(
      fieldName: 'country',
      fieldType: 'String',
      nullable: true,
    ),
  );

  //
  //
  //

  final Field field;

  //
  //
  //

  const ModelAddressEntryFields(this.field);

  //
  //
  //

  String get fieldName => this.field.fieldName!;
}
