//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_event.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelEvent extends _ModelEvent {
  //
  //
  //

  static const CLASS_NAME = 'ModelEvent';

  @override
  String get $className => CLASS_NAME;

  final String? id;
  final DataRefModel? ref;
  final ModelQueryable? displayName;
  final Color? displayColor;
  final String? description;
  final ModelRegistration? archivedGReg;
  final ModelRegistration? createdGReg;
  final ModelRegistration? deletedGReg;
  final ModelRegistration? updatedGReg;
  final DateTime? expiresAt;
  final Set<String>? memberPids;
  final Set<String>? tags;
  final ModelEnum? contentType;
  final Model? content;
  final List<ModelRegistration>? readRegs;
  final List<ModelRegistration>? archivedRegs;
  final List<ModelRegistration>? hiddenRegs;
  final List<ModelRegistration>? likedRegs;
  final List<ModelRegistration>? receivedRegs;

  //
  //
  //

  const ModelEvent({
    this.id,
    this.ref,
    this.displayName,
    this.displayColor,
    this.description,
    this.archivedGReg,
    this.createdGReg,
    this.deletedGReg,
    this.updatedGReg,
    this.expiresAt,
    this.memberPids,
    this.tags,
    this.contentType,
    this.content,
    this.readRegs,
    this.archivedRegs,
    this.hiddenRegs,
    this.likedRegs,
    this.receivedRegs,
  });

  const ModelEvent.c2({
    this.id,
    this.ref,
    this.displayName,
    this.displayColor,
    this.description,
    this.archivedGReg,
    this.createdGReg,
    this.deletedGReg,
    this.updatedGReg,
    this.expiresAt,
    this.memberPids,
    this.tags,
    this.contentType,
    this.content,
    this.readRegs,
    this.archivedRegs,
    this.hiddenRegs,
    this.likedRegs,
    this.receivedRegs,
  });

  factory ModelEvent.c3({
    String? id,
    DataRefModel? ref,
    ModelQueryable? displayName,
    Color? displayColor,
    String? description,
    ModelRegistration? archivedGReg,
    ModelRegistration? createdGReg,
    ModelRegistration? deletedGReg,
    ModelRegistration? updatedGReg,
    DateTime? expiresAt,
    Set<String>? memberPids,
    Set<String>? tags,
    ModelEnum? contentType,
    Model? content,
    List<ModelRegistration>? readRegs,
    List<ModelRegistration>? archivedRegs,
    List<ModelRegistration>? hiddenRegs,
    List<ModelRegistration>? likedRegs,
    List<ModelRegistration>? receivedRegs,
  }) {
    return ModelEvent(
      id: id,
      ref: ref,
      displayName: displayName,
      displayColor: displayColor,
      description: description,
      archivedGReg: archivedGReg,
      createdGReg: createdGReg,
      deletedGReg: deletedGReg,
      updatedGReg: updatedGReg,
      expiresAt: expiresAt,
      memberPids: memberPids,
      tags: tags,
      contentType: contentType,
      content: content,
      readRegs: readRegs,
      archivedRegs: archivedRegs,
      hiddenRegs: hiddenRegs,
      likedRegs: likedRegs,
      receivedRegs: receivedRegs,
    );
  }

  factory ModelEvent.from(
    BaseModel? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelEvent.from: $e');
      rethrow;
    }
  }

  static ModelEvent? fromOrNull(
    BaseModel? other,
  ) {
    return fromJsonOrNull(other?.toJson())!;
  }

  factory ModelEvent.of(
    ModelEvent other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelEvent.of: $e');
      rethrow;
    }
  }

  static ModelEvent? ofOrNull(
    ModelEvent? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  factory ModelEvent.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, 'ModelEvent.fromJsonString: $e');
      rethrow;
    }
  }

  static ModelEvent? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelEvent.fromJson(decoded);
      } else {
        return const ModelEvent.c2();
      }
    } catch (_) {
      return null;
    }
  }

  factory ModelEvent.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, 'ModelEvent.fromJson: $e');
      rethrow;
    }
  }

  static ModelEvent? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      final id0 = otherData?[ModelEventFields.id.name];
      final id = id0?.toString().trim().nullIfEmpty;
      final ref0 = otherData?[ModelEventFields.ref.name];
      final ref = () {
        final a = letMap<String, dynamic>(ref0);
        return a != null ? DataRefModel.fromJson(a) : null;
      }();
      final displayName0 = otherData?[ModelEventFields.displayName.name];
      final displayName = () {
        final a = letMap<String, dynamic>(displayName0);
        return a != null ? ModelQueryable.fromJson(a) : null;
      }();
      final displayColor0 = otherData?[ModelEventFields.displayColor.name];
      final displayColor = () {
        final a = letAs<int>(displayColor0);
        return a is int ? Color(a) : null;
      }();
      final description0 = otherData?[ModelEventFields.description.name];
      final description = description0?.toString().trim().nullIfEmpty;
      final archivedGReg0 = otherData?[ModelEventFields.archivedGReg.name];
      final archivedGReg = () {
        final a = letMap<String, dynamic>(archivedGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final createdGReg0 = otherData?[ModelEventFields.createdGReg.name];
      final createdGReg = () {
        final a = letMap<String, dynamic>(createdGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final deletedGReg0 = otherData?[ModelEventFields.deletedGReg.name];
      final deletedGReg = () {
        final a = letMap<String, dynamic>(deletedGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final updatedGReg0 = otherData?[ModelEventFields.updatedGReg.name];
      final updatedGReg = () {
        final a = letMap<String, dynamic>(updatedGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final expiresAt0 = otherData?[ModelEventFields.expiresAt.name];
      final expiresAt = () {
        final a = expiresAt0;
        return a != null ? DateTime.tryParse(a)?.toUtc() : null;
      }();
      final memberPids0 = otherData?[ModelEventFields.memberPids.name];
      final memberPids = letSet(memberPids0)
          ?.map(
            (p0) => p0?.toString().trim().nullIfEmpty,
          )
          .nonNulls
          .nullIfEmpty
          ?.toSet();
      final tags0 = otherData?[ModelEventFields.tags.name];
      final tags = letSet(tags0)
          ?.map(
            (p0) => p0?.toString().trim().nullIfEmpty,
          )
          .nonNulls
          .nullIfEmpty
          ?.toSet();
      final contentType0 = otherData?[ModelEventFields.contentType.name];
      final contentType = () {
        final a = letMap<String, dynamic>(contentType0);
        return a != null ? ModelEnum.fromJson(a) : null;
      }();
      final content0 = otherData?[ModelEventFields.content.name];
      final content = () {
        final a = letMap<String, dynamic>(content0);
        return a != null ? Model.fromJson(a) : null;
      }();
      final readRegs0 = otherData?[ModelEventFields.readRegs.name];
      final readRegs = letList(readRegs0)
          ?.map(
            (p0) => () {
              final a = letMap<String, dynamic>(p0);
              return a != null ? ModelRegistration.fromJson(a) : null;
            }(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final archivedRegs0 = otherData?[ModelEventFields.archivedRegs.name];
      final archivedRegs = letList(archivedRegs0)
          ?.map(
            (p0) => () {
              final a = letMap<String, dynamic>(p0);
              return a != null ? ModelRegistration.fromJson(a) : null;
            }(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final hiddenRegs0 = otherData?[ModelEventFields.hiddenRegs.name];
      final hiddenRegs = letList(hiddenRegs0)
          ?.map(
            (p0) => () {
              final a = letMap<String, dynamic>(p0);
              return a != null ? ModelRegistration.fromJson(a) : null;
            }(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final likedRegs0 = otherData?[ModelEventFields.likedRegs.name];
      final likedRegs = letList(likedRegs0)
          ?.map(
            (p0) => () {
              final a = letMap<String, dynamic>(p0);
              return a != null ? ModelRegistration.fromJson(a) : null;
            }(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final receivedRegs0 = otherData?[ModelEventFields.receivedRegs.name];
      final receivedRegs = letList(receivedRegs0)
          ?.map(
            (p0) => () {
              final a = letMap<String, dynamic>(p0);
              return a != null ? ModelRegistration.fromJson(a) : null;
            }(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      return ModelEvent(
        id: id,
        ref: ref,
        displayName: displayName,
        displayColor: displayColor,
        description: description,
        archivedGReg: archivedGReg,
        createdGReg: createdGReg,
        deletedGReg: deletedGReg,
        updatedGReg: updatedGReg,
        expiresAt: expiresAt,
        memberPids: memberPids,
        tags: tags,
        contentType: contentType,
        content: content,
        readRegs: readRegs,
        archivedRegs: archivedRegs,
        hiddenRegs: hiddenRegs,
        likedRegs: likedRegs,
        receivedRegs: receivedRegs,
      );
    } catch (e) {
      return null;
    }
  }

  factory ModelEvent.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, 'ModelEvent.fromUri: $e');
      rethrow;
    }
  }

  static ModelEvent? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS_NAME) {
        return ModelEvent.fromJson(uri.queryParameters);
      } else {
        return const ModelEvent.c2();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final id0 = this.id?.trim().nullIfEmpty;
      final ref0 = this.ref?.toJson();
      final displayName0 = this.displayName?.toJson();
      final displayColor0 = this.displayColor?.value;
      final description0 = this.description?.trim().nullIfEmpty;
      final archivedGReg0 = this.archivedGReg?.toJson();
      final createdGReg0 = this.createdGReg?.toJson();
      final deletedGReg0 = this.deletedGReg?.toJson();
      final updatedGReg0 = this.updatedGReg?.toJson();
      final expiresAt0 = this.expiresAt?.toUtc()?.toIso8601String();
      final memberPids0 = this
          .memberPids
          ?.map(
            (p0) => p0?.trim().nullIfEmpty,
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final tags0 = this
          .tags
          ?.map(
            (p0) => p0?.trim().nullIfEmpty,
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final contentType0 = this.contentType?.toJson();
      final content0 = this.content?.toJson();
      final readRegs0 = this
          .readRegs
          ?.map(
            (p0) => p0?.toJson(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final archivedRegs0 = this
          .archivedRegs
          ?.map(
            (p0) => p0?.toJson(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final hiddenRegs0 = this
          .hiddenRegs
          ?.map(
            (p0) => p0?.toJson(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final likedRegs0 = this
          .likedRegs
          ?.map(
            (p0) => p0?.toJson(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final receivedRegs0 = this
          .receivedRegs
          ?.map(
            (p0) => p0?.toJson(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final withNulls = <String, dynamic>{
        ModelEventFields.id.name: id0,
        ModelEventFields.ref.name: ref0,
        ModelEventFields.displayName.name: displayName0,
        ModelEventFields.displayColor.name: displayColor0,
        ModelEventFields.description.name: description0,
        ModelEventFields.archivedGReg.name: archivedGReg0,
        ModelEventFields.createdGReg.name: createdGReg0,
        ModelEventFields.deletedGReg.name: deletedGReg0,
        ModelEventFields.updatedGReg.name: updatedGReg0,
        ModelEventFields.expiresAt.name: expiresAt0,
        ModelEventFields.memberPids.name: memberPids0,
        ModelEventFields.tags.name: tags0,
        ModelEventFields.contentType.name: contentType0,
        ModelEventFields.content.name: content0,
        ModelEventFields.readRegs.name: readRegs0,
        ModelEventFields.archivedRegs.name: archivedRegs0,
        ModelEventFields.hiddenRegs.name: hiddenRegs0,
        ModelEventFields.likedRegs.name: likedRegs0,
        ModelEventFields.receivedRegs.name: receivedRegs0,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, 'ModelEvent.toJson: $e');
      rethrow;
    }
  }

  //
  //
  //

  @override
  ModelEvent copyWith(BaseModel? other) {
    final a = this.toJson();
    final b = other?.toJson();
    final c = {...a, ...?b};
    return ModelEvent.fromJson(c);
  }

  //
  //
  //

  // id.
  String? get idField => this.id;

  // ref.
  DataRefModel? get refField => this.ref;

  // displayName.
  ModelQueryable? get displayNameField => this.displayName;

  // displayColor.
  Color? get displayColorField => this.displayColor;

  // description.
  String? get descriptionField => this.description;

  // archivedGReg.
  ModelRegistration? get archivedGRegField => this.archivedGReg;

  // createdGReg.
  ModelRegistration? get createdGRegField => this.createdGReg;

  // deletedGReg.
  ModelRegistration? get deletedGRegField => this.deletedGReg;

  // updatedGReg.
  ModelRegistration? get updatedGRegField => this.updatedGReg;

  // expiresAt.
  DateTime? get expiresAtField => this.expiresAt;

  // memberPids.
  Set<String>? get memberPidsField => this.memberPids;

  // tags.
  Set<String>? get tagsField => this.tags;

  // contentType.
  ModelEnum? get contentTypeField => this.contentType;

  // content.
  Model? get contentField => this.content;

  // readRegs.
  List<ModelRegistration>? get readRegsField => this.readRegs;

  // archivedRegs.
  List<ModelRegistration>? get archivedRegsField => this.archivedRegs;

  // hiddenRegs.
  List<ModelRegistration>? get hiddenRegsField => this.hiddenRegs;

  // likedRegs.
  List<ModelRegistration>? get likedRegsField => this.likedRegs;

  // receivedRegs.
  List<ModelRegistration>? get receivedRegsField => this.receivedRegs;
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

enum ModelEventFields {
  //
  //
  //

  id(
    const Field(
      fieldName: 'id',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  ref(
    const Field(
      fieldName: 'ref',
      fieldType: 'DataRefModel',
      nullable: true,
    ),
  ),
  displayName(
    const Field(
      fieldName: 'displayName',
      fieldType: 'ModelQueryable',
      nullable: true,
    ),
  ),
  displayColor(
    const Field(
      fieldName: 'displayColor',
      fieldType: 'Color',
      nullable: true,
    ),
  ),
  description(
    const Field(
      fieldName: 'description',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  archivedGReg(
    const Field(
      fieldName: 'archivedGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  createdGReg(
    const Field(
      fieldName: 'createdGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  deletedGReg(
    const Field(
      fieldName: 'deletedGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  updatedGReg(
    const Field(
      fieldName: 'updatedGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  expiresAt(
    const Field(
      fieldName: 'expiresAt',
      fieldType: 'DateTime',
      nullable: true,
    ),
  ),
  memberPids(
    const Field(
      fieldName: 'memberPids',
      fieldType: 'Set<String>',
      nullable: true,
    ),
  ),
  tags(
    const Field(
      fieldName: 'tags',
      fieldType: 'Set<String>',
      nullable: true,
    ),
  ),
  contentType(
    const Field(
      fieldName: 'contentType',
      fieldType: 'ModelEnum',
      nullable: true,
    ),
  ),
  content(
    const Field(
      fieldName: 'content',
      fieldType: 'Model',
      nullable: true,
    ),
  ),
  readRegs(
    const Field(
      fieldName: 'readRegs',
      fieldType: 'List<ModelRegistration>',
      nullable: true,
    ),
  ),
  archivedRegs(
    const Field(
      fieldName: 'archivedRegs',
      fieldType: 'List<ModelRegistration>',
      nullable: true,
    ),
  ),
  hiddenRegs(
    const Field(
      fieldName: 'hiddenRegs',
      fieldType: 'List<ModelRegistration>',
      nullable: true,
    ),
  ),
  likedRegs(
    const Field(
      fieldName: 'likedRegs',
      fieldType: 'List<ModelRegistration>',
      nullable: true,
    ),
  ),
  receivedRegs(
    const Field(
      fieldName: 'receivedRegs',
      fieldType: 'List<ModelRegistration>',
      nullable: true,
    ),
  );

  //
  //
  //

  final Field field;

  //
  //
  //

  const ModelEventFields(this.field);

  //
  //
  //

  String get fieldName => this.field.fieldName!;
}
