//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_user_rel_def.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelUserRelDef extends _ModelUserRelDef {
  //
  //
  //

  static const CLASS = 'ModelUserRelDef';
  static const MODEL_ID = 'model_user_rel_def';

  static const K_ID = 'id';
  static const K_PERMISSIONS = 'permissions';

  ModelUserPermissions? permissions;

  //
  //
  //

  ModelUserRelDef({
    String? id,
    this.permissions,
  }) {
    this.id = id;
  }

  //
  //
  //

  ModelUserRelDef.unsafe({
    String? id,
    this.permissions,
  }) {
    this.id = id;
  }

  //
  //
  //

  factory ModelUserRelDef.from(
    Model? other,
  ) {
    return ModelUserRelDef.unsafe()..updateWith(other);
  }

  //
  //
  //

  factory ModelUserRelDef.of(
    ModelUserRelDef? other,
  ) {
    return ModelUserRelDef.unsafe()..updateWith(other);
  }

  //
  //
  //

  factory ModelUserRelDef.fromJsonString(
    String? source,
  ) {
    try {
      if (source != null && source.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelUserRelDef.fromJson(decoded);
      } else {
        return ModelUserRelDef.unsafe();
      }
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  factory ModelUserRelDef.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return ModelUserRelDef.unsafe(
        id: otherData?[K_ID]?.toString().trim().nullIfEmpty,
        permissions: () {
          final a = letMap<String, dynamic>(otherData?[K_PERMISSIONS]);
          return a != null ? ModelUserPermissions.fromJson(a) : null;
        }(),
      );
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_ID: id?.toString().trim().nullIfEmpty,
        K_PERMISSIONS: permissions?.toJson(),
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return ModelUserRelDef.unsafe() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (ModelUserRelDef.unsafe()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  void updateWithJson(
    Map<String, dynamic>? otherData,
  ) {
    if (otherData != null && otherData.isNotEmpty) {
      final other = ModelUserRelDef.fromJson(otherData);
      other.id != null ? this.id = other.id : null;
      other.permissions != null ? this.permissions = other.permissions : null;
    }
  }
}
