//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_invitation_link_details.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelInvitationLinkDetails extends Model {
  //
  //
  //

  static const CLASS = 'ModelInvitationLinkDetails';
  static const MODEL_ID = 'model_invitation_link_details';

  static const K_DEF = 'def';
  static const K_DEF_TYPE = 'def_type';
  static const K_FROM_PUB_ID = 'from_pub_id';
  static const K_ID = 'id';
  static const K_STATUS = 'status';
  static const K_TO_PUB_ID = 'to_pub_id';

  GenericModel? def;
  InvitationDefType? defType;
  String? fromPubId;
  InvitationStatusType? status;
  String? toPubId;

  //
  //
  //

  ModelInvitationLinkDetails({
    String? id,
    this.def,
    this.defType,
    this.fromPubId,
    this.status,
    this.toPubId,
  }) {
    this.id = id;
  }

  //
  //
  //

  ModelInvitationLinkDetails.unsafe({
    String? id,
    this.def,
    this.defType,
    this.fromPubId,
    this.status,
    this.toPubId,
  }) {
    this.id = id;
  }

  //
  //
  //

  factory ModelInvitationLinkDetails.from(
    Model? other,
  ) {
    if (other is DataModel) {
      return ModelInvitationLinkDetails.fromDataModel(other);
    } else {
      return ModelInvitationLinkDetails.unsafe()..updateWith(other);
    }
  }

  //
  //
  //

  factory ModelInvitationLinkDetails.of(
    ModelInvitationLinkDetails? other,
  ) {
    return ModelInvitationLinkDetails.unsafe()..updateWith(other);
  }

  //
  //
  //

  factory ModelInvitationLinkDetails.fromJsonString(
    String? source,
  ) {
    try {
      if (source != null && source.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelInvitationLinkDetails.fromJson(decoded);
      } else {
        return ModelInvitationLinkDetails.unsafe();
      }
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  factory ModelInvitationLinkDetails.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return ModelInvitationLinkDetails.unsafe(
        def: () {
          final a = letMap<String, dynamic>(otherData?[K_DEF]);
          return a != null ? GenericModel.fromJson(a) : null;
        }(),
        defType: InvitationDefType.values
            .valueOf(letAs<String>(otherData?[K_DEF_TYPE])),
        fromPubId: otherData?[K_FROM_PUB_ID]?.toString().trim().nullIfEmpty,
        id: otherData?[K_ID]?.toString().trim().nullIfEmpty,
        status: InvitationStatusType.values
            .valueOf(letAs<String>(otherData?[K_STATUS])),
        toPubId: otherData?[K_TO_PUB_ID]?.toString().trim().nullIfEmpty,
      );
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  factory ModelInvitationLinkDetails.fromDataModel(
    DataModel? other,
  ) {
    return ModelInvitationLinkDetails.fromJson(other?.data ?? {});
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_DEF: def?.toJson(),
        K_DEF_TYPE: defType?.name,
        K_FROM_PUB_ID: fromPubId?.toString().trim().nullIfEmpty,
        K_ID: id?.toString().trim().nullIfEmpty,
        K_STATUS: status?.name,
        K_TO_PUB_ID: toPubId?.toString().trim().nullIfEmpty,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return ModelInvitationLinkDetails.unsafe() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (ModelInvitationLinkDetails.unsafe()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  void updateWithJson(
    Map<String, dynamic>? otherData,
  ) {
    if (otherData != null && otherData.isNotEmpty) {
      final other = ModelInvitationLinkDetails.fromJson(otherData);
      other.def != null ? this.def = other.def : null;
      other.defType != null ? this.defType = other.defType : null;
      other.fromPubId != null ? this.fromPubId = other.fromPubId : null;
      other.id != null ? this.id = other.id : null;
      other.status != null ? this.status = other.status : null;
      other.toPubId != null ? this.toPubId = other.toPubId : null;
    }
  }
}
