//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_admin_org_rel_def.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelAdminOrgRelDef extends _ModelAdminOrgRelDef {
  //
  //
  //

  static const CLASS = 'ModelAdminOrgRelDef';
  static const MODEL_ID = 'model_admin_org_rel_def';

  static const K_ADMIN_PUB_ID = 'admin_pub_id';
  static const K_ID = 'id';
  static const K_ORGANIZATION_PUB_ID = 'organization_pub_id';

  String? adminPubId;
  String? organizationPubId;

  //
  //
  //

  ModelAdminOrgRelDef({
    String? id,
    this.adminPubId,
    this.organizationPubId,
  }) {
    this.id = id;
  }

  //
  //
  //

  ModelAdminOrgRelDef.unsafe({
    String? id,
    this.adminPubId,
    this.organizationPubId,
  }) {
    this.id = id;
  }

  //
  //
  //

  factory ModelAdminOrgRelDef.from(
    Model? other,
  ) {
    return ModelAdminOrgRelDef.unsafe()..updateWith(other);
  }

  //
  //
  //

  factory ModelAdminOrgRelDef.of(
    ModelAdminOrgRelDef? other,
  ) {
    return ModelAdminOrgRelDef.unsafe()..updateWith(other);
  }

  //
  //
  //

  factory ModelAdminOrgRelDef.fromJsonString(
    String? source,
  ) {
    try {
      if (source != null && source.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelAdminOrgRelDef.fromJson(decoded);
      } else {
        return ModelAdminOrgRelDef.unsafe();
      }
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  factory ModelAdminOrgRelDef.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return ModelAdminOrgRelDef.unsafe(
        adminPubId: otherData?[K_ADMIN_PUB_ID]?.toString().trim().nullIfEmpty,
        id: otherData?[K_ID]?.toString().trim().nullIfEmpty,
        organizationPubId:
            otherData?[K_ORGANIZATION_PUB_ID]?.toString().trim().nullIfEmpty,
      );
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_ADMIN_PUB_ID: adminPubId?.toString().trim().nullIfEmpty,
        K_ID: id?.toString().trim().nullIfEmpty,
        K_ORGANIZATION_PUB_ID: organizationPubId?.toString().trim().nullIfEmpty,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return ModelAdminOrgRelDef.unsafe() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (ModelAdminOrgRelDef.unsafe()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  void updateWithJson(
    Map<String, dynamic>? otherData,
  ) {
    if (otherData != null && otherData.isNotEmpty) {
      final other = ModelAdminOrgRelDef.fromJson(otherData);
      other.adminPubId != null ? this.adminPubId = other.adminPubId : null;
      other.id != null ? this.id = other.id : null;
      other.organizationPubId != null
          ? this.organizationPubId = other.organizationPubId
          : null;
    }
  }
}
