//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GENIE
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

import '/_common.dart';

part '_entry_model.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

const ENTRY_MODEL_FIELDS = {
  ...DISPLAY_MODEL_FIELDS,
  ('archived_g_reg?', ModelRegistration),
  ('created_g_reg?', ModelRegistration),
  ('deleted_g_reg?', ModelRegistration),
  ('update_g_reg?', ModelRegistration),
};

@GenerateModel(
  shouldInherit: true,
  fields: ENTRY_MODEL_FIELDS,
)
// ignore: unused_element
abstract class _EntryModel extends Model implements DisplayModel {}
