//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GENIE
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: unused_element

import '/_common.dart';

part '_google_places_data_model.g.dart';
part '_google_places_term_model.g.dart';
part '_google_places_prediction_model.g.dart';
part '_google_places_matched_substring_model.g.dart';
part '_google_places_structured_formatting_model.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

@GenerateModel(
  shouldInherit: true,
  keyStringCase: LOWER_SNAKE_CASE,
  fields: {
    Field(
      fieldPath: ['description'],
      fieldType: String,
    ),
    Field(
      fieldPath: ['matched_substrings'],
      fieldType: List<GooglePlacesMatchedSubstringModel>,
    ),
    Field(
      fieldPath: ['place_id'],
      fieldType: String,
    ),
    Field(
      fieldPath: ['reference'],
      fieldType: String,
    ),
    Field(
      fieldPath: ['structured_formatting'],
      fieldType: GooglePlacesStructuredFormattingModel,
    ),
    Field(
      fieldPath: ['terms'],
      fieldType: List<GooglePlacesTermModel>,
    ),
    Field(
      fieldPath: ['types'],
      fieldType: List<String>,
    ),
  },
)
abstract class _GooglePlacesPredictionModel extends Model {
  const _GooglePlacesPredictionModel();
}

@GenerateModel(
  shouldInherit: true,
  keyStringCase: LOWER_SNAKE_CASE,
  fields: {
    Field(
      fieldPath: ['length'],
      fieldType: int,
    ),
    Field(
      fieldPath: ['offset'],
      fieldType: int,
    ),
  },
)
abstract class _GooglePlacesMatchedSubstringModel extends Model {
  const _GooglePlacesMatchedSubstringModel();
}

@GenerateModel(
  shouldInherit: true,
  keyStringCase: LOWER_SNAKE_CASE,
  fields: {
    Field(
      fieldPath: ['main_text'],
      fieldType: String,
    ),
    Field(
      fieldPath: ['main_text_matched_substrings'],
      fieldType: List<GooglePlacesMatchedSubstringModel>,
    ),
    Field(
      fieldPath: ['secondary_text'],
      fieldType: String,
    ),
  },
)
abstract class _GooglePlacesStructuredFormattingModel extends Model {
  const _GooglePlacesStructuredFormattingModel();
}

@GenerateModel(
  shouldInherit: true,
  keyStringCase: LOWER_SNAKE_CASE,
  fields: {
    Field(
      fieldPath: ['offset'],
      fieldType: int,
    ),
    Field(
      fieldPath: ['value'],
      fieldType: String,
    ),
  },
)
abstract class _GooglePlacesTermModel extends Model {
  const _GooglePlacesTermModel();
}

@GenerateModel(
  shouldInherit: true,
  keyStringCase: LOWER_SNAKE_CASE,
  fields: {
    Field(
      fieldPath: ['predictions'],
      fieldType: List<GooglePlacesPredictionModel>,
    ),
    Field(
      fieldPath: ['status'],
      fieldType: String,
    ),
  },
)
abstract class _GooglePlacesDataModel extends Model {
  const _GooglePlacesDataModel();
}
