//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_invitation.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelInvitation extends _ModelInvitation {
  //
  //
  //

  static const CLASS_NAME = 'ModelInvitation';

  @override
  String get $className => CLASS_NAME;

  final String? id;
  final DataRefModel? ref;
  final ModelQueryable? displayName;
  final Color? displayColor;
  final String? description;
  final ModelRegistration? archivedGReg;
  final ModelRegistration? createdGReg;
  final ModelRegistration? deletedGReg;
  final ModelRegistration? updatedGReg;
  final DateTime? expiresAt;
  final ModelEnum? contentType;
  final Model? content;
  final Uri? invitationLink;
  final Set<ModelQueryable>? inviteeEmails;
  final Set<ModelQueryable>? inviteeAcceptedEmails;
  final Set<ModelQueryable>? inviteeRejectedEmails;

  //
  //
  //

  const ModelInvitation({
    this.id,
    this.ref,
    this.displayName,
    this.displayColor,
    this.description,
    this.archivedGReg,
    this.createdGReg,
    this.deletedGReg,
    this.updatedGReg,
    this.expiresAt,
    this.contentType,
    this.content,
    this.invitationLink,
    this.inviteeEmails,
    this.inviteeAcceptedEmails,
    this.inviteeRejectedEmails,
  });

  const ModelInvitation.c2({
    this.id,
    this.ref,
    this.displayName,
    this.displayColor,
    this.description,
    this.archivedGReg,
    this.createdGReg,
    this.deletedGReg,
    this.updatedGReg,
    this.expiresAt,
    this.contentType,
    this.content,
    this.invitationLink,
    this.inviteeEmails,
    this.inviteeAcceptedEmails,
    this.inviteeRejectedEmails,
  });

  factory ModelInvitation.c3({
    String? id,
    DataRefModel? ref,
    ModelQueryable? displayName,
    Color? displayColor,
    String? description,
    ModelRegistration? archivedGReg,
    ModelRegistration? createdGReg,
    ModelRegistration? deletedGReg,
    ModelRegistration? updatedGReg,
    DateTime? expiresAt,
    ModelEnum? contentType,
    Model? content,
    Uri? invitationLink,
    Set<ModelQueryable>? inviteeEmails,
    Set<ModelQueryable>? inviteeAcceptedEmails,
    Set<ModelQueryable>? inviteeRejectedEmails,
  }) {
    return ModelInvitation(
      id: id,
      ref: ref,
      displayName: displayName,
      displayColor: displayColor,
      description: description,
      archivedGReg: archivedGReg,
      createdGReg: createdGReg,
      deletedGReg: deletedGReg,
      updatedGReg: updatedGReg,
      expiresAt: expiresAt,
      contentType: contentType,
      content: content,
      invitationLink: invitationLink,
      inviteeEmails: inviteeEmails,
      inviteeAcceptedEmails: inviteeAcceptedEmails,
      inviteeRejectedEmails: inviteeRejectedEmails,
    );
  }

  factory ModelInvitation.from(
    BaseModel? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelInvitation.from: $e');
      rethrow;
    }
  }

  static ModelInvitation? fromOrNull(
    BaseModel? other,
  ) {
    return fromJsonOrNull(other?.toJson())!;
  }

  factory ModelInvitation.of(
    ModelInvitation other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelInvitation.of: $e');
      rethrow;
    }
  }

  static ModelInvitation? ofOrNull(
    ModelInvitation? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  factory ModelInvitation.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, 'ModelInvitation.fromJsonString: $e');
      rethrow;
    }
  }

  static ModelInvitation? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelInvitation.fromJson(decoded);
      } else {
        return const ModelInvitation.c2();
      }
    } catch (_) {
      return null;
    }
  }

  factory ModelInvitation.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, 'ModelInvitation.fromJson: $e');
      rethrow;
    }
  }

  static ModelInvitation? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      final id0 = otherData?[ModelInvitationFields.id.name];
      final id = id0?.toString().trim().nullIfEmpty;
      final ref0 = otherData?[ModelInvitationFields.ref.name];
      final ref = () {
        final a = letMap<String, dynamic>(ref0);
        return a != null ? DataRefModel.fromJson(a) : null;
      }();
      final displayName0 = otherData?[ModelInvitationFields.displayName.name];
      final displayName = () {
        final a = letMap<String, dynamic>(displayName0);
        return a != null ? ModelQueryable.fromJson(a) : null;
      }();
      final displayColor0 = otherData?[ModelInvitationFields.displayColor.name];
      final displayColor = () {
        final a = letAs<int>(displayColor0);
        return a is int ? Color(a) : null;
      }();
      final description0 = otherData?[ModelInvitationFields.description.name];
      final description = description0?.toString().trim().nullIfEmpty;
      final archivedGReg0 = otherData?[ModelInvitationFields.archivedGReg.name];
      final archivedGReg = () {
        final a = letMap<String, dynamic>(archivedGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final createdGReg0 = otherData?[ModelInvitationFields.createdGReg.name];
      final createdGReg = () {
        final a = letMap<String, dynamic>(createdGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final deletedGReg0 = otherData?[ModelInvitationFields.deletedGReg.name];
      final deletedGReg = () {
        final a = letMap<String, dynamic>(deletedGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final updatedGReg0 = otherData?[ModelInvitationFields.updatedGReg.name];
      final updatedGReg = () {
        final a = letMap<String, dynamic>(updatedGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final expiresAt0 = otherData?[ModelInvitationFields.expiresAt.name];
      final expiresAt = () {
        final a = expiresAt0;
        return a != null ? DateTime.tryParse(a)?.toUtc() : null;
      }();
      final contentType0 = otherData?[ModelInvitationFields.contentType.name];
      final contentType = () {
        final a = letMap<String, dynamic>(contentType0);
        return a != null ? ModelEnum.fromJson(a) : null;
      }();
      final content0 = otherData?[ModelInvitationFields.content.name];
      final content = () {
        final a = letMap<String, dynamic>(content0);
        return a != null ? Model.fromJson(a) : null;
      }();
      final invitationLink0 =
          otherData?[ModelInvitationFields.invitationLink.name];
      final invitationLink = () {
        final a = invitationLink0;
        return a is String ? a.trim().nullIfEmpty?.toUriOrNull() : null;
      }();
      final inviteeEmails0 =
          otherData?[ModelInvitationFields.inviteeEmails.name];
      final inviteeEmails = letSet(inviteeEmails0)
          ?.map(
            (p0) => () {
              final a = letMap<String, dynamic>(p0);
              return a != null ? ModelQueryable.fromJson(a) : null;
            }(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toSet();
      final inviteeAcceptedEmails0 =
          otherData?[ModelInvitationFields.inviteeAcceptedEmails.name];
      final inviteeAcceptedEmails = letSet(inviteeAcceptedEmails0)
          ?.map(
            (p0) => () {
              final a = letMap<String, dynamic>(p0);
              return a != null ? ModelQueryable.fromJson(a) : null;
            }(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toSet();
      final inviteeRejectedEmails0 =
          otherData?[ModelInvitationFields.inviteeRejectedEmails.name];
      final inviteeRejectedEmails = letSet(inviteeRejectedEmails0)
          ?.map(
            (p0) => () {
              final a = letMap<String, dynamic>(p0);
              return a != null ? ModelQueryable.fromJson(a) : null;
            }(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toSet();
      return ModelInvitation(
        id: id,
        ref: ref,
        displayName: displayName,
        displayColor: displayColor,
        description: description,
        archivedGReg: archivedGReg,
        createdGReg: createdGReg,
        deletedGReg: deletedGReg,
        updatedGReg: updatedGReg,
        expiresAt: expiresAt,
        contentType: contentType,
        content: content,
        invitationLink: invitationLink,
        inviteeEmails: inviteeEmails,
        inviteeAcceptedEmails: inviteeAcceptedEmails,
        inviteeRejectedEmails: inviteeRejectedEmails,
      );
    } catch (e) {
      return null;
    }
  }

  factory ModelInvitation.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, 'ModelInvitation.fromUri: $e');
      rethrow;
    }
  }

  static ModelInvitation? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS_NAME) {
        return ModelInvitation.fromJson(uri.queryParameters);
      } else {
        return const ModelInvitation.c2();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final id0 = this.id?.trim().nullIfEmpty;
      final ref0 = this.ref?.toJson();
      final displayName0 = this.displayName?.toJson();
      final displayColor0 = this.displayColor?.value;
      final description0 = this.description?.trim().nullIfEmpty;
      final archivedGReg0 = this.archivedGReg?.toJson();
      final createdGReg0 = this.createdGReg?.toJson();
      final deletedGReg0 = this.deletedGReg?.toJson();
      final updatedGReg0 = this.updatedGReg?.toJson();
      final expiresAt0 = this.expiresAt?.toUtc()?.toIso8601String();
      final contentType0 = this.contentType?.toJson();
      final content0 = this.content?.toJson();
      final invitationLink0 = this.invitationLink?.toString();
      final inviteeEmails0 = this
          .inviteeEmails
          ?.map(
            (p0) => p0?.toJson(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final inviteeAcceptedEmails0 = this
          .inviteeAcceptedEmails
          ?.map(
            (p0) => p0?.toJson(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final inviteeRejectedEmails0 = this
          .inviteeRejectedEmails
          ?.map(
            (p0) => p0?.toJson(),
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final withNulls = <String, dynamic>{
        ModelInvitationFields.id.name: id0,
        ModelInvitationFields.ref.name: ref0,
        ModelInvitationFields.displayName.name: displayName0,
        ModelInvitationFields.displayColor.name: displayColor0,
        ModelInvitationFields.description.name: description0,
        ModelInvitationFields.archivedGReg.name: archivedGReg0,
        ModelInvitationFields.createdGReg.name: createdGReg0,
        ModelInvitationFields.deletedGReg.name: deletedGReg0,
        ModelInvitationFields.updatedGReg.name: updatedGReg0,
        ModelInvitationFields.expiresAt.name: expiresAt0,
        ModelInvitationFields.contentType.name: contentType0,
        ModelInvitationFields.content.name: content0,
        ModelInvitationFields.invitationLink.name: invitationLink0,
        ModelInvitationFields.inviteeEmails.name: inviteeEmails0,
        ModelInvitationFields.inviteeAcceptedEmails.name:
            inviteeAcceptedEmails0,
        ModelInvitationFields.inviteeRejectedEmails.name:
            inviteeRejectedEmails0,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, 'ModelInvitation.toJson: $e');
      rethrow;
    }
  }

  //
  //
  //

  @override
  ModelInvitation copyWith(BaseModel? other) {
    final a = this.toJson();
    final b = other?.toJson();
    final c = {...a, ...?b};
    return ModelInvitation.fromJson(c);
  }

  //
  //
  //

  // id.
  String? get idField => this.id;

  // ref.
  DataRefModel? get refField => this.ref;

  // displayName.
  ModelQueryable? get displayNameField => this.displayName;

  // displayColor.
  Color? get displayColorField => this.displayColor;

  // description.
  String? get descriptionField => this.description;

  // archivedGReg.
  ModelRegistration? get archivedGRegField => this.archivedGReg;

  // createdGReg.
  ModelRegistration? get createdGRegField => this.createdGReg;

  // deletedGReg.
  ModelRegistration? get deletedGRegField => this.deletedGReg;

  // updatedGReg.
  ModelRegistration? get updatedGRegField => this.updatedGReg;

  // expiresAt.
  DateTime? get expiresAtField => this.expiresAt;

  // contentType.
  ModelEnum? get contentTypeField => this.contentType;

  // content.
  Model? get contentField => this.content;

  // invitationLink.
  Uri? get invitationLinkField => this.invitationLink;

  // inviteeEmails.
  Set<ModelQueryable>? get inviteeEmailsField => this.inviteeEmails;

  // inviteeAcceptedEmails.
  Set<ModelQueryable>? get inviteeAcceptedEmailsField =>
      this.inviteeAcceptedEmails;

  // inviteeRejectedEmails.
  Set<ModelQueryable>? get inviteeRejectedEmailsField =>
      this.inviteeRejectedEmails;
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

enum ModelInvitationFields {
  //
  //
  //

  id(
    const Field(
      fieldName: 'id',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  ref(
    const Field(
      fieldName: 'ref',
      fieldType: 'DataRefModel',
      nullable: true,
    ),
  ),
  displayName(
    const Field(
      fieldName: 'displayName',
      fieldType: 'ModelQueryable',
      nullable: true,
    ),
  ),
  displayColor(
    const Field(
      fieldName: 'displayColor',
      fieldType: 'Color',
      nullable: true,
    ),
  ),
  description(
    const Field(
      fieldName: 'description',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  archivedGReg(
    const Field(
      fieldName: 'archivedGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  createdGReg(
    const Field(
      fieldName: 'createdGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  deletedGReg(
    const Field(
      fieldName: 'deletedGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  updatedGReg(
    const Field(
      fieldName: 'updatedGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  expiresAt(
    const Field(
      fieldName: 'expiresAt',
      fieldType: 'DateTime',
      nullable: true,
    ),
  ),
  contentType(
    const Field(
      fieldName: 'contentType',
      fieldType: 'ModelEnum',
      nullable: true,
    ),
  ),
  content(
    const Field(
      fieldName: 'content',
      fieldType: 'Model',
      nullable: true,
    ),
  ),
  invitationLink(
    const Field(
      fieldName: 'invitationLink',
      fieldType: 'Uri',
      nullable: true,
    ),
  ),
  inviteeEmails(
    const Field(
      fieldName: 'inviteeEmails',
      fieldType: 'Set<ModelQueryable>',
      nullable: true,
    ),
  ),
  inviteeAcceptedEmails(
    const Field(
      fieldName: 'inviteeAcceptedEmails',
      fieldType: 'Set<ModelQueryable>',
      nullable: true,
    ),
  ),
  inviteeRejectedEmails(
    const Field(
      fieldName: 'inviteeRejectedEmails',
      fieldType: 'Set<ModelQueryable>',
      nullable: true,
    ),
  );

  //
  //
  //

  final Field field;

  //
  //
  //

  const ModelInvitationFields(this.field);

  //
  //
  //

  String get fieldName => this.field.fieldName!;
}
