//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GENIE
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

import '/_common.dart';

part '_model_invitation.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

@GenerateModel(
  shouldInherit: true,
  fields: {
    ('ref', DataRefModel),
    ('id?', String),
    ('created_reg', ModelRegistration),
    ('expires_at?', DateTime),
    ('type?', InvitationType),
    ('body?', DataModel),
    ('invitation_link?', Uri),
    ('invitee_emails?', 'Set<ModelQueryable>'),
    ('invitee_accepted_emails?', 'Set<ModelQueryable>'),
    ('invitee_rejected_emails?', 'Set<ModelQueryable>'),
  },
)
abstract class _ModelInvitation extends ThisModel<ModelInvitation> {
  //
  //
  //

  bool get isExpired => this.model.expiresAt?.isBefore(DateTime.now()) ?? false;
}
