//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_media.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelMedia extends _ModelMedia {
  //
  //
  //

  static const CLASS = 'ModelMedia';
  static const MODEL_ID = 'model_media';

  static const K_CREATED_AT = 'created_at';
  static const K_CREATOR_ID = 'creator_id';
  static const K_DESCRIPTION = 'description';
  static const K_DISPLAY_NAME = 'display_name';
  static const K_DISPLAY_NAME_SEARCHABLE = 'display_name_searchable';
  static const K_FILE_NAME = 'file_name';
  static const K_ID = 'id';
  static const K_MIME_TYPE = 'mime_type';
  static const K_URL = 'url';

  DateTime? createdAt;
  String? creatorId;
  String? description;
  String? displayName;
  String? displayNameSearchable;
  String? fileName;
  String? mimeType;
  String? url;

  //
  //
  //

  ModelMedia({
    String? id,
    this.createdAt,
    this.creatorId,
    this.description,
    this.displayName,
    this.displayNameSearchable,
    this.fileName,
    this.mimeType,
    this.url,
  }) {
    this.id = id;
  }

  //
  //
  //

  ModelMedia.unsafe({
    String? id,
    this.createdAt,
    this.creatorId,
    this.description,
    this.displayName,
    this.displayNameSearchable,
    this.fileName,
    this.mimeType,
    this.url,
  }) {
    this.id = id;
  }

  //
  //
  //

  factory ModelMedia.from(
    Model? other,
  ) {
    return ModelMedia.fromJson(
      other is GenericModel ? other.data : other?.toJson(),
    );
  }

  //
  //
  //

  factory ModelMedia.of(
    ModelMedia? other,
  ) {
    return ModelMedia.fromJson(other?.toJson());
  }

  //
  //
  //

  factory ModelMedia.fromJsonString(
    String? source,
  ) {
    try {
      if (source != null && source.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelMedia.fromJson(decoded);
      } else {
        return ModelMedia.unsafe();
      }
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  factory ModelMedia.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return ModelMedia.unsafe(
        createdAt: () {
          final a = otherData?[K_CREATED_AT];
          return a != null ? DateTime.tryParse(a)?.toUtc() : null;
        }(),
        creatorId: otherData?[K_CREATOR_ID]?.toString().trim().nullIfEmpty,
        description: otherData?[K_DESCRIPTION]?.toString().trim().nullIfEmpty,
        displayName: otherData?[K_DISPLAY_NAME]?.toString().trim().nullIfEmpty,
        displayNameSearchable: otherData?[K_DISPLAY_NAME_SEARCHABLE]
            ?.toString()
            .trim()
            .nullIfEmpty
            ?.toLowerCase(),
        fileName: otherData?[K_FILE_NAME]?.toString().trim().nullIfEmpty,
        id: otherData?[K_ID]?.toString().trim().nullIfEmpty,
        mimeType: otherData?[K_MIME_TYPE]?.toString().trim().nullIfEmpty,
        url: otherData?[K_URL]?.toString().trim().nullIfEmpty,
      );
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  factory ModelMedia.fromUri(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == MODEL_ID) {
        return ModelMedia.fromJson(uri.queryParameters);
      } else {
        return ModelMedia.unsafe();
      }
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  static ModelMedia? convert(
    Model? other,
  ) {
    return other != null ? ModelMedia.from(other) : null;
  }

  //
  //
  //

  static ModelMedia? fromPool({
    required Iterable<ModelMedia>? pool,
    required String? id,
  }) {
    return id != null ? pool?.firstWhereOrNull((e) => e.id == id) : null;
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_CREATED_AT: createdAt?.toUtc()?.toIso8601String(),
        K_CREATOR_ID: creatorId?.toString().trim().nullIfEmpty,
        K_DESCRIPTION: description?.toString().trim().nullIfEmpty,
        K_DISPLAY_NAME: displayName?.toString().trim().nullIfEmpty,
        K_DISPLAY_NAME_SEARCHABLE:
            displayNameSearchable?.toString().trim().nullIfEmpty?.toLowerCase(),
        K_FILE_NAME: fileName?.toString().trim().nullIfEmpty,
        K_ID: id?.toString().trim().nullIfEmpty,
        K_MIME_TYPE: mimeType?.toString().trim().nullIfEmpty,
        K_URL: url?.toString().trim().nullIfEmpty,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return ModelMedia.unsafe() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (ModelMedia.unsafe()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  void updateWithJson(
    Map<String, dynamic>? otherData,
  ) {
    if (otherData != null && otherData.isNotEmpty) {
      final other = ModelMedia.fromJson(otherData);
      other.createdAt != null ? this.createdAt = other.createdAt : null;
      other.creatorId != null ? this.creatorId = other.creatorId : null;
      other.description != null ? this.description = other.description : null;
      other.displayName != null ? this.displayName = other.displayName : null;
      other.displayNameSearchable != null
          ? this.displayNameSearchable = other.displayNameSearchable
          : null;
      other.fileName != null ? this.fileName = other.fileName : null;
      other.id != null ? this.id = other.id : null;
      other.mimeType != null ? this.mimeType = other.mimeType : null;
      other.url != null ? this.url = other.url : null;
    }
  }

  //
  //
  //

  String get modelId => MODEL_ID;
}
