//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of "access_type.dart";

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

extension AccessTypeUtils on AccessType {
  AccessType get next {
    final index = (this.index + 1) % AccessType.values.length;
    return AccessType.values[index];
  }

  AccessType get previous {
    final index =
        (this.index - 1 + AccessType.values.length) % AccessType.values.length;
    return AccessType.values[index];
  }

  String get translated {
    return "${this.name}||types.$this".tr();
  }

  String get friendlyName {
    return this
        .name
        .toSnakeCase()
        .split("_")
        .map((e) => e.capitalize())
        .join(" ");
  }
}
