//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GENIE
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

import '/_common.dart';

part '_model_address_entry.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

@GenerateModel(
  shouldInherit: true,
  fields: {
    ...KFields.title,
    ...KFields.title_searchable,
    ...KFields.created_at,
    ...KFields.created_by,
    // Name of the recipient.
    'name': 'String?',
    // Primary address field (street address or P.O. box).
    'address_line_1': 'String?',
    // Secondary address field (apartment, suite, unit).
    'address_line_2': 'String?',
    // City or locality.
    'city': 'String?',
    // State, province, or regional equivalent.
    'state_or_province': 'String?',
    // Postal or ZIP code.
    'postal_code': 'String?',
    // Country name.
    'country': 'String?',
    // Additional information or delivery instructions.
    'notes': 'String?',
  },
)
abstract class _ModelAddressEntry extends ThisModel<ModelAddressEntry> {}
