//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_user.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelUser extends _ModelUser {
  //
  //
  //

  static const CLASS_NAME = 'ModelUser';

  @override
  String get $className => CLASS_NAME;

  final String? id;
  final DataRefModel? ref;
  final ModelQueryable? displayName;
  final Color? displayColor;
  final String? description;
  final ModelRegistration? archivedGReg;
  final ModelRegistration? createdGReg;
  final ModelRegistration? deletedGReg;
  final ModelRegistration? updatedGReg;
  final DateTime? expiresAt;
  final String? pid;
  final String? seed;
  final bool? didSendWelcomeEmail;
  final Set<String>? emailSubscriptions;
  final Set<String>? pushSubscriptions;
  final Set<String>? smsSubscriptions;

  //
  //
  //

  const ModelUser({
    this.id,
    this.ref,
    this.displayName,
    this.displayColor,
    this.description,
    this.archivedGReg,
    this.createdGReg,
    this.deletedGReg,
    this.updatedGReg,
    this.expiresAt,
    this.pid,
    this.seed,
    this.didSendWelcomeEmail,
    this.emailSubscriptions,
    this.pushSubscriptions,
    this.smsSubscriptions,
  });

  const ModelUser.c2({
    this.id,
    this.ref,
    this.displayName,
    this.displayColor,
    this.description,
    this.archivedGReg,
    this.createdGReg,
    this.deletedGReg,
    this.updatedGReg,
    this.expiresAt,
    this.pid,
    this.seed,
    this.didSendWelcomeEmail,
    this.emailSubscriptions,
    this.pushSubscriptions,
    this.smsSubscriptions,
  });

  factory ModelUser.c3({
    String? id,
    DataRefModel? ref,
    ModelQueryable? displayName,
    Color? displayColor,
    String? description,
    ModelRegistration? archivedGReg,
    ModelRegistration? createdGReg,
    ModelRegistration? deletedGReg,
    ModelRegistration? updatedGReg,
    DateTime? expiresAt,
    String? pid,
    String? seed,
    bool? didSendWelcomeEmail,
    Set<String>? emailSubscriptions,
    Set<String>? pushSubscriptions,
    Set<String>? smsSubscriptions,
  }) {
    return ModelUser(
      id: id,
      ref: ref,
      displayName: displayName,
      displayColor: displayColor,
      description: description,
      archivedGReg: archivedGReg,
      createdGReg: createdGReg,
      deletedGReg: deletedGReg,
      updatedGReg: updatedGReg,
      expiresAt: expiresAt,
      pid: pid,
      seed: seed,
      didSendWelcomeEmail: didSendWelcomeEmail,
      emailSubscriptions: emailSubscriptions,
      pushSubscriptions: pushSubscriptions,
      smsSubscriptions: smsSubscriptions,
    );
  }

  factory ModelUser.from(
    BaseModel? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelUser.from: $e');
      rethrow;
    }
  }

  static ModelUser? fromOrNull(
    BaseModel? other,
  ) {
    return fromJsonOrNull(other?.toJson())!;
  }

  factory ModelUser.of(
    ModelUser other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelUser.of: $e');
      rethrow;
    }
  }

  static ModelUser? ofOrNull(
    ModelUser? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  factory ModelUser.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, 'ModelUser.fromJsonString: $e');
      rethrow;
    }
  }

  static ModelUser? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelUser.fromJson(decoded);
      } else {
        return const ModelUser.c2();
      }
    } catch (_) {
      return null;
    }
  }

  factory ModelUser.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, 'ModelUser.fromJson: $e');
      rethrow;
    }
  }

  static ModelUser? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      final id0 = otherData?[ModelUserFields.id.name];
      final id = id0?.toString().trim().nullIfEmpty;
      final ref0 = otherData?[ModelUserFields.ref.name];
      final ref = () {
        final a = letMap<String, dynamic>(ref0);
        return a != null ? DataRefModel.fromJson(a) : null;
      }();
      final displayName0 = otherData?[ModelUserFields.displayName.name];
      final displayName = () {
        final a = letMap<String, dynamic>(displayName0);
        return a != null ? ModelQueryable.fromJson(a) : null;
      }();
      final displayColor0 = otherData?[ModelUserFields.displayColor.name];
      final displayColor = () {
        final a = letAs<int>(displayColor0);
        return a is int ? Color(a) : null;
      }();
      final description0 = otherData?[ModelUserFields.description.name];
      final description = description0?.toString().trim().nullIfEmpty;
      final archivedGReg0 = otherData?[ModelUserFields.archivedGReg.name];
      final archivedGReg = () {
        final a = letMap<String, dynamic>(archivedGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final createdGReg0 = otherData?[ModelUserFields.createdGReg.name];
      final createdGReg = () {
        final a = letMap<String, dynamic>(createdGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final deletedGReg0 = otherData?[ModelUserFields.deletedGReg.name];
      final deletedGReg = () {
        final a = letMap<String, dynamic>(deletedGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final updatedGReg0 = otherData?[ModelUserFields.updatedGReg.name];
      final updatedGReg = () {
        final a = letMap<String, dynamic>(updatedGReg0);
        return a != null ? ModelRegistration.fromJson(a) : null;
      }();
      final expiresAt0 = otherData?[ModelUserFields.expiresAt.name];
      final expiresAt = () {
        final a = expiresAt0;
        return a != null ? DateTime.tryParse(a)?.toUtc() : null;
      }();
      final pid0 = otherData?[ModelUserFields.pid.name];
      final pid = pid0?.toString().trim().nullIfEmpty;
      final seed0 = otherData?[ModelUserFields.seed.name];
      final seed = seed0?.toString().trim().nullIfEmpty;
      final didSendWelcomeEmail0 =
          otherData?[ModelUserFields.didSendWelcomeEmail.name];
      final didSendWelcomeEmail = letBool(didSendWelcomeEmail0);
      final emailSubscriptions0 =
          otherData?[ModelUserFields.emailSubscriptions.name];
      final emailSubscriptions = letSet(emailSubscriptions0)
          ?.map(
            (p0) => p0?.toString().trim().nullIfEmpty,
          )
          .nonNulls
          .nullIfEmpty
          ?.toSet();
      final pushSubscriptions0 =
          otherData?[ModelUserFields.pushSubscriptions.name];
      final pushSubscriptions = letSet(pushSubscriptions0)
          ?.map(
            (p0) => p0?.toString().trim().nullIfEmpty,
          )
          .nonNulls
          .nullIfEmpty
          ?.toSet();
      final smsSubscriptions0 =
          otherData?[ModelUserFields.smsSubscriptions.name];
      final smsSubscriptions = letSet(smsSubscriptions0)
          ?.map(
            (p0) => p0?.toString().trim().nullIfEmpty,
          )
          .nonNulls
          .nullIfEmpty
          ?.toSet();
      return ModelUser(
        id: id,
        ref: ref,
        displayName: displayName,
        displayColor: displayColor,
        description: description,
        archivedGReg: archivedGReg,
        createdGReg: createdGReg,
        deletedGReg: deletedGReg,
        updatedGReg: updatedGReg,
        expiresAt: expiresAt,
        pid: pid,
        seed: seed,
        didSendWelcomeEmail: didSendWelcomeEmail,
        emailSubscriptions: emailSubscriptions,
        pushSubscriptions: pushSubscriptions,
        smsSubscriptions: smsSubscriptions,
      );
    } catch (e) {
      return null;
    }
  }

  factory ModelUser.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, 'ModelUser.fromUri: $e');
      rethrow;
    }
  }

  static ModelUser? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS_NAME) {
        return ModelUser.fromJson(uri.queryParameters);
      } else {
        return const ModelUser.c2();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final id0 = this.id?.trim().nullIfEmpty;
      final ref0 = this.ref?.toJson();
      final displayName0 = this.displayName?.toJson();
      final displayColor0 = this.displayColor?.value;
      final description0 = this.description?.trim().nullIfEmpty;
      final archivedGReg0 = this.archivedGReg?.toJson();
      final createdGReg0 = this.createdGReg?.toJson();
      final deletedGReg0 = this.deletedGReg?.toJson();
      final updatedGReg0 = this.updatedGReg?.toJson();
      final expiresAt0 = this.expiresAt?.toUtc()?.toIso8601String();
      final pid0 = this.pid?.trim().nullIfEmpty;
      final seed0 = this.seed?.trim().nullIfEmpty;
      final didSendWelcomeEmail0 = this.didSendWelcomeEmail;
      final emailSubscriptions0 = this
          .emailSubscriptions
          ?.map(
            (p0) => p0?.trim().nullIfEmpty,
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final pushSubscriptions0 = this
          .pushSubscriptions
          ?.map(
            (p0) => p0?.trim().nullIfEmpty,
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final smsSubscriptions0 = this
          .smsSubscriptions
          ?.map(
            (p0) => p0?.trim().nullIfEmpty,
          )
          .nonNulls
          .nullIfEmpty
          ?.toList();
      final withNulls = <String, dynamic>{
        ModelUserFields.id.name: id0,
        ModelUserFields.ref.name: ref0,
        ModelUserFields.displayName.name: displayName0,
        ModelUserFields.displayColor.name: displayColor0,
        ModelUserFields.description.name: description0,
        ModelUserFields.archivedGReg.name: archivedGReg0,
        ModelUserFields.createdGReg.name: createdGReg0,
        ModelUserFields.deletedGReg.name: deletedGReg0,
        ModelUserFields.updatedGReg.name: updatedGReg0,
        ModelUserFields.expiresAt.name: expiresAt0,
        ModelUserFields.pid.name: pid0,
        ModelUserFields.seed.name: seed0,
        ModelUserFields.didSendWelcomeEmail.name: didSendWelcomeEmail0,
        ModelUserFields.emailSubscriptions.name: emailSubscriptions0,
        ModelUserFields.pushSubscriptions.name: pushSubscriptions0,
        ModelUserFields.smsSubscriptions.name: smsSubscriptions0,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, 'ModelUser.toJson: $e');
      rethrow;
    }
  }

  //
  //
  //

  @override
  ModelUser copyWith(BaseModel? other) {
    final a = this.toJson();
    final b = other?.toJson();
    final c = {...a, ...?b};
    return ModelUser.fromJson(c);
  }

  //
  //
  //

  // id.
  String? get idField => this.id;

  // ref.
  DataRefModel? get refField => this.ref;

  // displayName.
  ModelQueryable? get displayNameField => this.displayName;

  // displayColor.
  Color? get displayColorField => this.displayColor;

  // description.
  String? get descriptionField => this.description;

  // archivedGReg.
  ModelRegistration? get archivedGRegField => this.archivedGReg;

  // createdGReg.
  ModelRegistration? get createdGRegField => this.createdGReg;

  // deletedGReg.
  ModelRegistration? get deletedGRegField => this.deletedGReg;

  // updatedGReg.
  ModelRegistration? get updatedGRegField => this.updatedGReg;

  // expiresAt.
  DateTime? get expiresAtField => this.expiresAt;

  // pid.
  String? get pidField => this.pid;

  // seed.
  String? get seedField => this.seed;

  // didSendWelcomeEmail.
  bool? get didSendWelcomeEmailField => this.didSendWelcomeEmail;

  // emailSubscriptions.
  Set<String>? get emailSubscriptionsField => this.emailSubscriptions;

  // pushSubscriptions.
  Set<String>? get pushSubscriptionsField => this.pushSubscriptions;

  // smsSubscriptions.
  Set<String>? get smsSubscriptionsField => this.smsSubscriptions;
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

enum ModelUserFields {
  //
  //
  //

  id(
    const Field(
      fieldName: 'id',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  ref(
    const Field(
      fieldName: 'ref',
      fieldType: 'DataRefModel',
      nullable: true,
    ),
  ),
  displayName(
    const Field(
      fieldName: 'displayName',
      fieldType: 'ModelQueryable',
      nullable: true,
    ),
  ),
  displayColor(
    const Field(
      fieldName: 'displayColor',
      fieldType: 'Color',
      nullable: true,
    ),
  ),
  description(
    const Field(
      fieldName: 'description',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  archivedGReg(
    const Field(
      fieldName: 'archivedGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  createdGReg(
    const Field(
      fieldName: 'createdGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  deletedGReg(
    const Field(
      fieldName: 'deletedGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  updatedGReg(
    const Field(
      fieldName: 'updatedGReg',
      fieldType: 'ModelRegistration',
      nullable: true,
    ),
  ),
  expiresAt(
    const Field(
      fieldName: 'expiresAt',
      fieldType: 'DateTime',
      nullable: true,
    ),
  ),
  pid(
    const Field(
      fieldName: 'pid',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  seed(
    const Field(
      fieldName: 'seed',
      fieldType: 'String',
      nullable: true,
    ),
  ),
  didSendWelcomeEmail(
    const Field(
      fieldName: 'didSendWelcomeEmail',
      fieldType: 'bool',
      nullable: true,
    ),
  ),
  emailSubscriptions(
    const Field(
      fieldName: 'emailSubscriptions',
      fieldType: 'Set<String>',
      nullable: true,
    ),
  ),
  pushSubscriptions(
    const Field(
      fieldName: 'pushSubscriptions',
      fieldType: 'Set<String>',
      nullable: true,
    ),
  ),
  smsSubscriptions(
    const Field(
      fieldName: 'smsSubscriptions',
      fieldType: 'Set<String>',
      nullable: true,
    ),
  );

  //
  //
  //

  final Field field;

  //
  //
  //

  const ModelUserFields(this.field);

  //
  //
  //

  String get fieldName => this.field.fieldName!;
}
