//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'invitation_def_type.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

extension InvitationDefTypeUtils on InvitationDefType {
  InvitationDefType get next {
    final index = (this.index + 1) % InvitationDefType.values.length;
    return InvitationDefType.values[index];
  }

  InvitationDefType get previous {
    final index = (this.index - 1 + InvitationDefType.values.length) %
        InvitationDefType.values.length;
    return InvitationDefType.values[index];
  }

  String trFromSection(String section, [Map args = const {}]) {
    return '${this.friendlyName}||$section.${this.name}'.tr(args: args);
  }

  String get friendlyName {
    return this
        .name
        .toSnakeCase()
        .split('_')
        .map((e) => e.capitalize())
        .join(' ');
  }
}
